version: '3'

volumes:
  postgresql_volume:

networks:
  icecream-network:

services:
  icecream-postgresql:
    image: postgres:14.4
    container_name: icecream-postgresql
    ports:
      - ${ICECREAM_POSTGRESQL_PORT}:5432
    volumes:            
      - postgresql_volume:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${ICECREAM_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${ICECREAM_POSTGRESQL_PASSWORD} 
      POSTGRES_MULTIPLE_DATABASES: ${ICECREAM_POSTGRESQL_PRODUCT_DB},${ICECREAM_POSTGRESQL_SHIPPING_DB}
    networks:
      - icecream-network
  