version: '3'

volumes:
  icecream-postgresql-volume:

networks:
  icecream-network:

services:
  icecream-postgresql:
    container_name: icecream-postgresql
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    ports:
      - ${ICECREAM_POSTGRESQL_PORT}:5432
    volumes:            
      - icecream-postgresql-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${ICECREAM_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${ICECREAM_POSTGRESQL_PASSWORD} 
      POSTGRES_MULTIPLE_DATABASES: ${ICECREAM_POSTGRESQL_IDENTITY_DB},${ICECREAM_POSTGRESQL_PRODUCT_DB},${ICECREAM_POSTGRESQL_PAYMENT_DB}
    networks:
      - icecream-network
  