version: '3'

volumes:
  mainstream:

networks:
  Icecream_network:

services:
  Icecream-mainstream-datastore:
    image: mysql:8.0.28
    container_name: Icecream-mainstream-datastore
    restart: always
    ports:
      - ${ICECREAM_MAINSTREAM_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${ICECREAM_MAINSTREAM_ROOT_PASSWORD}
      MYSQL_USER: ${ICECREAM_MAINSTREAM_USER}
      MYSQL_PASSWORD: ${ICECREAM_MAINSTREAM_PASSWORD}
      MYSQL_MULTIPLE_DATABASES:  ${ICECREAM_MAINSTREAM_DB}
    volumes:
      - mainstream:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - Icecream_network
    cap_add:
        - SYS_NICE
    security_opt:
        - seccomp:unconfined
  