server:
  http2:
    enabled: true
  port: ${GATEWAY_PORT}
  error:
    include-message: always

spring:
  application:
    name: Icecream Gateway Service
    version: 0.1.0
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
      allowed-methods: GET,POST
      max-age: 3600
    cors:
      allow-credentials: true
      allowed-origins:
        - ${STOREFRONT_PROTOCOL}://${STOREFRONT_HOST}:${STOREFRONT_PORT}
        - ${BACKOFFICE_PROTOCOL}://${BACKOFFICE_HOST}:${BACKOFFICE_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    schema-registry-server: http://${SCHEMA_REGISTRY_HOST}:${SCHEMA_REGISTRY_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDENTITY_PROTOCOL}://${IDENTITY_HOST}:${IDENTITY_PORT}/realms/${IDENTITY_REALM}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: storefront
      principle-attribute: email

module:
  product:
    grpcUrl: ${PRODUCT_GRPC_HOST}:${PRODUCT_GRPC_PORT}
    httpUrl: ${PRODUCT_PROTOCOL}://${PRODUCT_HOST}:${PRODUCT_PORT}
  customer:
    grpcUrl: ${CUSTOMER_GRPC_HOST}:${CUSTOMER_GRPC_PORT}
    httpUrl: ${CUSTOMER_PROTOCOL}://${CUSTOMER_HOST}:${CUSTOMER_PORT}
  order:
    grpcUrl: ${ORDER_GRPC_HOST}:${ORDER_GRPC_PORT}
    httpUrl: ${ORDER_PROTOCOL}://${ORDER_HOST}:${ORDER_PORT}
